source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, "10.0"
use_frameworks!

target 'RxDemo' do

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Moya/RxSwift'
    pod 'Kingfisher'
    pod 'RxDataSources'

end